version: '3.8'

services:
  postgres:
    image: postgres:13  
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USERNAME}  
      POSTGRES_PASSWORD: ${PG_PASSWORD}  
      POSTGRES_DB: ${PG_DBNAME}  
    ports:
      - "${PG_PORT}:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${PG_DBNAME}",
          "-U",
          "${PG_USERNAME}"
        ]
      interval: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
    driver: local
