version: '3.8'

services:
  postgres:
    image: postgres:13  
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USERNAME}  
      POSTGRES_PASSWORD: ${PG_PASSWORD}  
      POSTGRES_DB: ${PG_DBNAME}  
    ports:
      - "${PG_PORT}:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
