version: 2

sources:
  - name: dbt_nyt_books
    database: nyt
    schema: public
    tables:
      - name: raw_books
        meta:
          dagster:
            asset_key: ["raw_books"] # This metadata specifies the corresponding Dagster asset for this dbt source.
