# name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your specific Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change to specific directory
        run: cd dagster_nyt_books

      - name: Run isort
        run: isort .

      - name: Run formatting
        run: black .

      - name: Run type checking
        run: mypy .

      - name: Run linting
        run: flake8 .

      - name: Run tests
        run: pytest
