version: 2

models:
  - name: stg_books
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: primar_isbn_13
        tests:
          - unique
          - not_null
