
name: 'dbt_nyt_books'
version: '1.0.0'

profile: 'dbt_nyt_books'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  dbt_nyt_books:
      mart:
        materialized: incremental
      staging:
        materialized: incremental

vars:
  'dbt_date:time_zone': 'Europe/London'

