dbt_nyt_books:
   outputs:
     dev:
       type: duckdb
       path: dev.duckdb
       threads: 1
 
     prod:
       type: postgres
       host: {{ process.env.PG_HOST }}
       user: {{ process.env.PG_USERNAME }}
       password: {{ process.env.PG_PASSWORD }}
       port: {{ process.env.PG_PORT }}
       dbname: {{ process.env.PG_DBNAME }}
       threads: 4
 
   target: prod

