dbt_nyt_books:
   outputs:
     dev:
       type: duckdb
       path: dev.duckdb
       threads: 1
 
     prod:
       type: postgres
       host: "{{ env_var('PG_HOST') }}" 
       user: "{{ env_var('PG_USERNAME') }}"
       password: "{{ env_var('PG_PASSWORD') }}" 
       port: "{{ env_var('PG_PORT') | as_number }}"  
       dbname: "{{ env_var('PG_DBNAME') }}"
       schema: public
       threads: 4
 
   target: prod

