# name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install dependencies
        working-directory: dagster_nyt_books
        run: |
          python -m pip install --upgrade pip
          pip install -e . -q

      - name: Run isort
        working-directory: dagster_nyt_books
        run: isort .

      - name: Run formatting
        working-directory: dagster_nyt_books
        run: black .

      - name: Run type checking
        working-directory: dagster_nyt_books
        run: mypy .

      - name: Run linting
        working-directory: dagster_nyt_books
        run: flake8 .
